# This file contains default values, and does not need to be edited. All
# important settings can be changed from the admin interface.

defaults: &defaults
  site_title: Gab Social
  site_short_description: ''
  site_description: ''
  site_contact_username: ''
  site_contact_email: ''
  registrations_mode: 'open'
  min_invite_role: 'admin'
  default_sensitive: false
  hide_network: false
  unfollow_modal: false
  boost_modal: false
  delete_modal: true
  auto_play_gif: true
  display_media: 'default'
  expand_spoilers: false
  preview_sensitive_media: false
  group_in_home_feed: true
  noindex: false
  aggregate_reblogs: true
  chat_messages:
    restrict_non_followers: true
    show_active: false
    read_receipts: false
    sounds: true
  notification_emails:
    follow: false
    reblog: false
    favourite: false
    mention: false
    follow_request: true
    digest: true
    report: true
    emails_from_gabcom: true
  interactions:
    must_be_follower: false
    must_be_following: false
    must_be_following_dm: false
  reserved_usernames:
    - about
    - account
    - accounts
    - admin
    - administrator
    - api
    - blocks
    - compose
    - filters
    - group
    - groups
    - help
    - home
    - inbox
    - intent
    - interact
    - invites
    - list
    - lists
    - manifest
    - media
    - mod
    - moderator
    - mutes
    - notifications
    - public
    - root
    - search
    - settings
    - share
    - src
    - support
    - tag
    - tags
    - timeline
    - user
    - username
    - users
    - webmaster
    - welcome
    - bookmarks
    - suggestions
    - link
    - links
    - messages
    - message
    - deck
  bootstrap_timeline_accounts: ''

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
